currently:
    - freelance (see below)
previously:
    - fellow at the <a href='http://www.ipea.gov.br/portal/index.php?option=com_content&Itemid=61'>Institute for Applied Economic Research (IPEA)</a> working on spatial economic simulation and transit demand modeling
    - Rhizome Seven-on-Seven (2018) participant
    - part-time faculty at The New School, teaching about simulation, systems thinking, and game design
    - Co-publisher of <a href='http://thenewinquiry.com/'><em>The New Inquiry</em></a>
    - Researcher-in-Residence at <a href='http://www.newinc.org/'>NEW INC</a>
    - <a href='http://www.ideas-city.org/'>IdeasCity</a> Athens fellow
    - DBRS Labs Researcher-in-Residence
    - Knight-Mozilla <a href='http://opennews.org/what/fellowships/2015meet/'>OpenNews Fellow</a> at The New York Times/Washington Post/<a href='http://coralproject.net/'>The Coral Project</a>
    - visiting faculty at the New School's Design+Journalism program (Fall 2014, Fall 2015)
    - <a href='https://knightfoundation.org/prototype/'>Knight Foundation Prototype Fund</a> grantee
    - interaction designer & developer at <a href='https://www.ideo.com/'>IDEO</a>
