currently:
    - freelance (see below)
    - fellow at the <a href='http://www.ipea.gov.br/portal/index.php?option=com_content&Itemid=61'>Institute for Applied Economic Research (IPEA)</a> working on spatial economic simulation and transit demand modeling
    - part-time faculty at The New School, teaching about simulation, systems thinking, and game design
previously:
    - co-publishing <a href='http://thenewinquiry.com/'><em>The New Inquiry</em></a>
    - Researcher-in-Residence @ <a href='http://www.newinc.org/'>NEW INC</a>
    - IdeasCity Athens fellow
    - DBRS Labs Researcher-in-Residence
    - Knight-Mozilla <a href='http://opennews.org/what/fellowships/2015meet/'>OpenNews Fellow</a> at The New York Times/Washington Post/<a href='http://coralproject.net/'>The Coral Project</a>
    - visiting faculty at the New School's Design+Journalism program (Fall 2014, Fall 2015)
    - Knight Foundation grantee
    - interaction designer & developer @ IDEO
