currently:
    - Lead independent researcher at the <a href="https://www.jainfamilyinstitute.org/"><img src="/assets/current/jfi.jpg">Jain Family Institute</a>
previously:
    - Rhizome <a href='https://rhizome.org/sevenonseven/'>Seven-on-Seven</a> (2018, Beijing) participant
    - Fellow at the <a href='http://www.ipea.gov.br/portal/index.php?option=com_content&Itemid=61'>Institute for Applied Economic Research (IPEA)</a> working on spatial economic simulation and transit demand modeling
    - Rhizome <a href='https://rhizome.org/sevenonseven/'>Seven-on-Seven</a> (2018, NYC) participant
    - Part-time faculty at <a href='https://www.newschool.edu/'>The New School</a>, teaching about simulation, systems thinking, and game design
    - Co-publisher of <a href='http://thenewinquiry.com/'><em>The New Inquiry</em></a>
    - Artist-in-Residence at <a href='http://sfpc.io/'>SFPC</a>
    - Researcher-in-Residence at <a href='http://www.newinc.org/'>NEW INC</a>
    - <a href='http://www.ideas-city.org/'>IdeasCity</a> Athens fellow
    - <a href='https://medium.com/dbrs-innovation-labs'>DBRS Innovation Labs</a> Researcher-in-Residence
    - Knight-Mozilla <a href='http://opennews.org/what/fellowships/2015meet/'>OpenNews Fellow</a> at The New York Times/Washington Post/<a href='http://coralproject.net/'>The Coral Project</a>
    - Visiting faculty at the <a href='https://www.newschool.edu/lang/journalism-design/'>New School's Design+Journalism</a> program (Fall 2014, Fall 2015)
    - <a href='https://knightfoundation.org/prototype/'>Knight Foundation Prototype Fund</a> grantee
    - Interaction designer & developer at <a href='https://www.ideo.com/'>IDEO</a>
