currently: "Researcher-in-Residence @ NEW INC"
upcoming: 'for hire: f[at]frnsys.com'
previously: "IdeasCity Athens, DBRS Labs Researcher-in-Residence, 2015 Knight-Mozilla <a href='http://opennews.org/what/fellowships/2015meet/'>OpenNews Fellow</a> at The New York Times/Washington Post/<a href='http://coralproject.net/'>The Coral Project</a>, visiting faculty at the New School's Design+Journalism program (Fall 2014, Fall 2015), IDEO, Knight Foundation grantee"
